### ISSUE TITLE
Overrides in wrong namespace

### ISSUE THREAD

**Issue by AlexReimann** [stonier/feed_the_troll#11]
[The overrides tag / name](https://github.com/stonier/feed_the_troll/blob/devel/parameters/demo_reconfiguration.yaml#L21) has to be the same as the namespace.

E. g. instead of:

```
service_namespace: /core/reconfiguration

parameters:
  trajectory_controller:
    module: gopher_trajectory_controller.cfg.TrajectoryControllerConfig
    namespace: reconfiguration/trajectory_controller

rajectory_controller:
  cmd_execution_delay_max:            0.250
```

I have to use:

```
.
.
.

reconfiguration/trajectory_controller/:
  cmd_execution_delay_max:            0.250
```

Or else the overrides don't work (because wrong namespace).

**Comment by stonier** [comment]
I have a better idea than this...  These name spaces are all too confusing and it doesn't make much sense to have the servers anywhere except /core/reconfiguration anyway.  I'll do some trickery with parameter reflection to make that work.

**Comment by stonier** [comment]
No longer relevant now 3f8b8236 is in. Parameters are reflected (and unreflected on deletion) over in the reconfiguration server's namespace, so no more having to point the server at a namespace. Yaml configuration now looks like:

```
# Point this feeder at the reconfiguration server - this is where the load/unload
# services can be found. It follws the usual ros namespacing conventions - i.e.
# it can be an absolute global name (e.g. /reconfiguration) or it can be
# representative of a sibling namespace as is the case here
server_namespace: reconfiguration

# Define your individual dyn-recfg servers here
parameters:

  # A dyn-recfg server definition - with this name it will be found at 'reconfiguration/dude'
  dude:
    # The dyn-recfg type (it is actually a python module) - don't forget the 'Config' suffix!
    module: feed_the_troll.cfg.DemoConfig
    # Load some initialisations to the param server that override those in the .cfg files
    overrides:
      int_param: 5
      double_param: 0.6
      str_param: Dude
      bool_param: False
      size: 2

  # Another dyn-recfg server definition - will be found at 'reconfiguration/dudette'
  dudette:
    module: feed_the_troll.cfg.DemoConfig
    overrides:
      int_param: 5
      double_param: 0.6
      str_param: Dudette
      bool_param: False
      size: 2
```
